name: api-yy
debug: false
port: 443
mode: production # set "production" for production env
our_epoch: 1352131200000

product: 693319382339586

wx_app_id:
  miniprogram: ""
  open_app: ""

password_login:
  username: ''
  password: ''
  account_id: '119'

app_version_require:
  s96qrl0lxc: "0.1"
  vtk79p06wy: "0.1"
  12yi4vjby0y: "0.1"

app_key_secret:
  1001: "4NjUpZ9RJiaayYir" # 订单分批接口
  1002: "QUAGIPYZv2phl5wJ" # pda
  1003: "JIBONJsfye7rO7nR" # WxProgram

backend:
  temp_filepath: "./tempfiles/"
  access_key: LTAIWjOyn670XM
  access_secret: PuHCEVoZMh8a6f6GMsUj7G86Vp
  bucket: ykd-img
  endpoint: oss-cn-beijing.aliyuncs.com
  # endpoint: oss-cn-beijing-internal.aliyuncs.com 内部免流量，部署时使用
  visit_host: https://img.youkangda.com # 访问域名

uploads_temp_path: "./_uploads/"

space:
    max_space: 10
    default_group_name: ""

feed:
  rn: 5
  expiration_at_hours: 48

avatar_file:
    min_width: 30
    max_size_width: 1000
    max_size_height: 1000

file:
    size: 104857600 # 100M
    min_width: 30
    max_width: 999999

membership:
    register_default_size: 1073741824 # 1G
    register_default_title: "注册"
    register_default_details: "新注册默认分配"

msgbox:
    msg_type:
        im: 1
        im_group: 2
        feed: 3
        system: 4
    per_page: 30

redis:
  db: 1
  max_connections: 100

  prefix: "api-gw"
  expire_list: 5
  expire_message: 120


server_status:
  api-gw:
  account-server:


