# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import pbaccount_pb2 as pbaccount__pb2


class AccountServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.HasProductAuthorize = channel.unary_unary(
        '/pbaccount.AccountService/HasProductAuthorize',
        request_serializer=pbaccount__pb2.ProductAuthorizeQueryRequest.SerializeToString,
        response_deserializer=pbaccount__pb2.ExistsResult.FromString,
        )
    self.ProductAuthorize = channel.unary_unary(
        '/pbaccount.AccountService/ProductAuthorize',
        request_serializer=pbaccount__pb2.ProductAuthorizeRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.ExistsAccount = channel.unary_unary(
        '/pbaccount.AccountService/ExistsAccount',
        request_serializer=pbaccount__pb2.AccountRequest.SerializeToString,
        response_deserializer=pbaccount__pb2.ExistsResult.FromString,
        )
    self.GetAccount = channel.unary_unary(
        '/pbaccount.AccountService/GetAccount',
        request_serializer=pbaccount__pb2.GetAccountRequest.SerializeToString,
        response_deserializer=pbaccount__pb2.Account.FromString,
        )
    self.AuthAccount = channel.unary_unary(
        '/pbaccount.AccountService/AuthAccount',
        request_serializer=pbaccount__pb2.AuthAccountRequest.SerializeToString,
        response_deserializer=pbaccount__pb2.Account.FromString,
        )
    self.AuthAccountToken = channel.unary_unary(
        '/pbaccount.AccountService/AuthAccountToken',
        request_serializer=pbaccount__pb2.AuthAccountTokenRequest.SerializeToString,
        response_deserializer=pbaccount__pb2.Account.FromString,
        )
    self.CreateAccount = channel.unary_unary(
        '/pbaccount.AccountService/CreateAccount',
        request_serializer=pbaccount__pb2.AccountCreateRequest.SerializeToString,
        response_deserializer=pbaccount__pb2.Account.FromString,
        )
    self.Update = channel.unary_unary(
        '/pbaccount.AccountService/Update',
        request_serializer=pbaccount__pb2.AccountUpdateRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.ChangePassword = channel.unary_unary(
        '/pbaccount.AccountService/ChangePassword',
        request_serializer=pbaccount__pb2.PasswordChangeRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.ResetPassword = channel.unary_unary(
        '/pbaccount.AccountService/ResetPassword',
        request_serializer=pbaccount__pb2.PasswordResetRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.UpdateAccountStatus = channel.unary_unary(
        '/pbaccount.AccountService/UpdateAccountStatus',
        request_serializer=pbaccount__pb2.AccountStatusRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.CreateAccountByPartnerAccount = channel.unary_unary(
        '/pbaccount.AccountService/CreateAccountByPartnerAccount',
        request_serializer=pbaccount__pb2.CreateAccountByPartnerAccountRequest.SerializeToString,
        response_deserializer=pbaccount__pb2.Account.FromString,
        )
    self.ExistsPartnerAccount = channel.unary_unary(
        '/pbaccount.AccountService/ExistsPartnerAccount',
        request_serializer=pbaccount__pb2.PartnerAccountRequest.SerializeToString,
        response_deserializer=pbaccount__pb2.ExistsResult.FromString,
        )
    self.AuthPartnerAccount = channel.unary_unary(
        '/pbaccount.AccountService/AuthPartnerAccount',
        request_serializer=pbaccount__pb2.PartnerAccountAuthRequest.SerializeToString,
        response_deserializer=pbaccount__pb2.Account.FromString,
        )
    self.PartnerAccountBind = channel.unary_unary(
        '/pbaccount.AccountService/PartnerAccountBind',
        request_serializer=pbaccount__pb2.PartnerAccountBindRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.UpdatePartnerAccountOriginData = channel.unary_unary(
        '/pbaccount.AccountService/UpdatePartnerAccountOriginData',
        request_serializer=pbaccount__pb2.PartnerAccountUpdateOriginDataRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.PartnerAccountRelease = channel.unary_unary(
        '/pbaccount.AccountService/PartnerAccountRelease',
        request_serializer=pbaccount__pb2.PartnerAccountReleaseRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.GetUserInfo = channel.unary_unary(
        '/pbaccount.AccountService/GetUserInfo',
        request_serializer=pbaccount__pb2.UserInfoRequest.SerializeToString,
        response_deserializer=pbaccount__pb2.UserInfo.FromString,
        )
    self.UpdateUserInfo = channel.unary_unary(
        '/pbaccount.AccountService/UpdateUserInfo',
        request_serializer=pbaccount__pb2.UserInfoUpdateRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.UpdateUserAvatar = channel.unary_unary(
        '/pbaccount.AccountService/UpdateUserAvatar',
        request_serializer=pbaccount__pb2.UserAvatarUpdateRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.UpdateUserDOB = channel.unary_unary(
        '/pbaccount.AccountService/UpdateUserDOB',
        request_serializer=pbaccount__pb2.UserDOBUpdateRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )


class AccountServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def HasProductAuthorize(self, request, context):
    """是否有某个产品的授权
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ProductAuthorize(self, request, context):
    """授权（或取消授权）用户使用某项功能。至于是否有权限，业务系统或者管理后台需要进行严格判断
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ExistsAccount(self, request, context):
    """-----------------------------------------------------------------------------------------------------------------

    是否存在某个账号。不管账号的状态，只要存在就确认存在。
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAccount(self, request, context):
    """获得账号信息，通过用户账号获取，不需要密码。注意：如果app_id参数不存在，则不能获取到用户的Token；需要进行认证的地方，业务系统应慎重调用，比如尽量调用AuthAccountToken接口
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AuthAccount(self, request, context):
    """账号认证，需要密码
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AuthAccountToken(self, request, context):
    """通过Token进行账号认证
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateAccount(self, request, context):
    """添加账号
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Update(self, request, context):
    """更新账号信息（不包括密码、第三方账号信息等）
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ChangePassword(self, request, context):
    """修改密码
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ResetPassword(self, request, context):
    """重置密码（不需要进行认证，业务系统应慎重调用）
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateAccountStatus(self, request, context):
    """更新账号状态（激活、未激活、锁定并暂停账号或封号、用户注销账号等）
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateAccountByPartnerAccount(self, request, context):
    """用第三方账号新建账号
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ExistsPartnerAccount(self, request, context):
    """是否存在第三方账号
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AuthPartnerAccount(self, request, context):
    """通过第三方账号进行认证
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PartnerAccountBind(self, request, context):
    """绑定第三方账号
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdatePartnerAccountOriginData(self, request, context):
    """修改第三方账号的origin_data
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PartnerAccountRelease(self, request, context):
    """解绑第三方账号
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetUserInfo(self, request, context):
    """-----------------------------------------------------------------------------------------------------------------

    获取用户信息（不需要token。因为如果需要TOKEN，则无法获取从属的用户信息。如家有宝贝记录产品里，宝宝也会独立建账号，但是无法登录，此时就不存在TOKEN）
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateUserInfo(self, request, context):
    """更新用户信息，不包括头像及生日（不需要token。因为如果需要TOKEN，则无法获取从属的用户信息。如家有宝贝记录产品里，宝宝也会独立建账号，但是无法登录，此时就不存在TOKEN）
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateUserAvatar(self, request, context):
    """设置头像（不需要token。因为如果需要TOKEN，则无法获取从属的用户信息。如家有宝贝记录产品里，宝宝也会独立建账号，但是无法登录，此时就不存在TOKEN）
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateUserDOB(self, request, context):
    """设置DOB（不需要token。因为如果需要TOKEN，则无法获取从属的用户信息。如家有宝贝记录产品里，宝宝也会独立建账号，但是无法登录，此时就不存在TOKEN）
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AccountServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'HasProductAuthorize': grpc.unary_unary_rpc_method_handler(
          servicer.HasProductAuthorize,
          request_deserializer=pbaccount__pb2.ProductAuthorizeQueryRequest.FromString,
          response_serializer=pbaccount__pb2.ExistsResult.SerializeToString,
      ),
      'ProductAuthorize': grpc.unary_unary_rpc_method_handler(
          servicer.ProductAuthorize,
          request_deserializer=pbaccount__pb2.ProductAuthorizeRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'ExistsAccount': grpc.unary_unary_rpc_method_handler(
          servicer.ExistsAccount,
          request_deserializer=pbaccount__pb2.AccountRequest.FromString,
          response_serializer=pbaccount__pb2.ExistsResult.SerializeToString,
      ),
      'GetAccount': grpc.unary_unary_rpc_method_handler(
          servicer.GetAccount,
          request_deserializer=pbaccount__pb2.GetAccountRequest.FromString,
          response_serializer=pbaccount__pb2.Account.SerializeToString,
      ),
      'AuthAccount': grpc.unary_unary_rpc_method_handler(
          servicer.AuthAccount,
          request_deserializer=pbaccount__pb2.AuthAccountRequest.FromString,
          response_serializer=pbaccount__pb2.Account.SerializeToString,
      ),
      'AuthAccountToken': grpc.unary_unary_rpc_method_handler(
          servicer.AuthAccountToken,
          request_deserializer=pbaccount__pb2.AuthAccountTokenRequest.FromString,
          response_serializer=pbaccount__pb2.Account.SerializeToString,
      ),
      'CreateAccount': grpc.unary_unary_rpc_method_handler(
          servicer.CreateAccount,
          request_deserializer=pbaccount__pb2.AccountCreateRequest.FromString,
          response_serializer=pbaccount__pb2.Account.SerializeToString,
      ),
      'Update': grpc.unary_unary_rpc_method_handler(
          servicer.Update,
          request_deserializer=pbaccount__pb2.AccountUpdateRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'ChangePassword': grpc.unary_unary_rpc_method_handler(
          servicer.ChangePassword,
          request_deserializer=pbaccount__pb2.PasswordChangeRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'ResetPassword': grpc.unary_unary_rpc_method_handler(
          servicer.ResetPassword,
          request_deserializer=pbaccount__pb2.PasswordResetRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'UpdateAccountStatus': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateAccountStatus,
          request_deserializer=pbaccount__pb2.AccountStatusRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'CreateAccountByPartnerAccount': grpc.unary_unary_rpc_method_handler(
          servicer.CreateAccountByPartnerAccount,
          request_deserializer=pbaccount__pb2.CreateAccountByPartnerAccountRequest.FromString,
          response_serializer=pbaccount__pb2.Account.SerializeToString,
      ),
      'ExistsPartnerAccount': grpc.unary_unary_rpc_method_handler(
          servicer.ExistsPartnerAccount,
          request_deserializer=pbaccount__pb2.PartnerAccountRequest.FromString,
          response_serializer=pbaccount__pb2.ExistsResult.SerializeToString,
      ),
      'AuthPartnerAccount': grpc.unary_unary_rpc_method_handler(
          servicer.AuthPartnerAccount,
          request_deserializer=pbaccount__pb2.PartnerAccountAuthRequest.FromString,
          response_serializer=pbaccount__pb2.Account.SerializeToString,
      ),
      'PartnerAccountBind': grpc.unary_unary_rpc_method_handler(
          servicer.PartnerAccountBind,
          request_deserializer=pbaccount__pb2.PartnerAccountBindRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'UpdatePartnerAccountOriginData': grpc.unary_unary_rpc_method_handler(
          servicer.UpdatePartnerAccountOriginData,
          request_deserializer=pbaccount__pb2.PartnerAccountUpdateOriginDataRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'PartnerAccountRelease': grpc.unary_unary_rpc_method_handler(
          servicer.PartnerAccountRelease,
          request_deserializer=pbaccount__pb2.PartnerAccountReleaseRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'GetUserInfo': grpc.unary_unary_rpc_method_handler(
          servicer.GetUserInfo,
          request_deserializer=pbaccount__pb2.UserInfoRequest.FromString,
          response_serializer=pbaccount__pb2.UserInfo.SerializeToString,
      ),
      'UpdateUserInfo': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateUserInfo,
          request_deserializer=pbaccount__pb2.UserInfoUpdateRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'UpdateUserAvatar': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateUserAvatar,
          request_deserializer=pbaccount__pb2.UserAvatarUpdateRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'UpdateUserDOB': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateUserDOB,
          request_deserializer=pbaccount__pb2.UserDOBUpdateRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'pbaccount.AccountService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
