# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import pbmembership_pb2 as membership__pb2


class MembershipServerStub(object):
  """service Membership
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SetStorageChange = channel.unary_unary(
        '/membership.MembershipServer/SetStorageChange',
        request_serializer=membership__pb2.StorageChange.SerializeToString,
        response_deserializer=membership__pb2.ResultOfAction.FromString,
        )
    self.SetTotalStorageChange = channel.unary_unary(
        '/membership.MembershipServer/SetTotalStorageChange',
        request_serializer=membership__pb2.StorageChange.SerializeToString,
        response_deserializer=membership__pb2.ResultOfAction.FromString,
        )
    self.GetStorage = channel.unary_unary(
        '/membership.MembershipServer/GetStorage',
        request_serializer=membership__pb2.AccountId.SerializeToString,
        response_deserializer=membership__pb2.Storage.FromString,
        )


class MembershipServerServicer(object):
  """service Membership
  """

  def SetStorageChange(self, request, context):
    """set storage_change
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetTotalStorageChange(self, request, context):
    """set total_storage_change
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetStorage(self, request, context):
    """get storage
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MembershipServerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SetStorageChange': grpc.unary_unary_rpc_method_handler(
          servicer.SetStorageChange,
          request_deserializer=membership__pb2.StorageChange.FromString,
          response_serializer=membership__pb2.ResultOfAction.SerializeToString,
      ),
      'SetTotalStorageChange': grpc.unary_unary_rpc_method_handler(
          servicer.SetTotalStorageChange,
          request_deserializer=membership__pb2.StorageChange.FromString,
          response_serializer=membership__pb2.ResultOfAction.SerializeToString,
      ),
      'GetStorage': grpc.unary_unary_rpc_method_handler(
          servicer.GetStorage,
          request_deserializer=membership__pb2.AccountId.FromString,
          response_serializer=membership__pb2.Storage.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'membership.MembershipServer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
