# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: membership.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='membership.proto',
  package='membership',
  syntax='proto3',
  serialized_pb=_b('\n\x10membership.proto\x12\nmembership\"Z\n\rStorageChange\x12\x12\n\naccount_id\x18\x01 \x01(\x03\x12\x15\n\rchanged_value\x18\x02 \x01(\x03\x12\r\n\x05title\x18\x03 \x01(\t\x12\x0f\n\x07\x64\x65tails\x18\x04 \x01(\t\"\x1f\n\tAccountId\x12\x12\n\naccount_id\x18\x01 \x01(\x03\"E\n\x07Storage\x12\x12\n\nsize_total\x18\x01 \x01(\x03\x12\x11\n\tsize_used\x18\x02 \x01(\x03\x12\x13\n\x0bsize_remain\x18\x03 \x01(\x03\"2\n\x0eResultOfAction\x12\x0f\n\x07is_done\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1e\n\x0c\x45xistsResult\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\x32\xed\x01\n\x10MembershipServer\x12K\n\x10SetStorageChange\x12\x19.membership.StorageChange\x1a\x1a.membership.ResultOfAction\"\x00\x12P\n\x15SetTotalStorageChange\x12\x19.membership.StorageChange\x1a\x1a.membership.ResultOfAction\"\x00\x12:\n\nGetStorage\x12\x15.membership.AccountId\x1a\x13.membership.Storage\"\x00\x62\x06proto3')
)




_STORAGECHANGE = _descriptor.Descriptor(
  name='StorageChange',
  full_name='membership.StorageChange',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='account_id', full_name='membership.StorageChange.account_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='changed_value', full_name='membership.StorageChange.changed_value', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title', full_name='membership.StorageChange.title', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='details', full_name='membership.StorageChange.details', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=122,
)


_ACCOUNTID = _descriptor.Descriptor(
  name='AccountId',
  full_name='membership.AccountId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='account_id', full_name='membership.AccountId.account_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=155,
)


_STORAGE = _descriptor.Descriptor(
  name='Storage',
  full_name='membership.Storage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='size_total', full_name='membership.Storage.size_total', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='size_used', full_name='membership.Storage.size_used', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='size_remain', full_name='membership.Storage.size_remain', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=226,
)


_RESULTOFACTION = _descriptor.Descriptor(
  name='ResultOfAction',
  full_name='membership.ResultOfAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_done', full_name='membership.ResultOfAction.is_done', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='membership.ResultOfAction.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=228,
  serialized_end=278,
)


_EXISTSRESULT = _descriptor.Descriptor(
  name='ExistsResult',
  full_name='membership.ExistsResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='exists', full_name='membership.ExistsResult.exists', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=280,
  serialized_end=310,
)

DESCRIPTOR.message_types_by_name['StorageChange'] = _STORAGECHANGE
DESCRIPTOR.message_types_by_name['AccountId'] = _ACCOUNTID
DESCRIPTOR.message_types_by_name['Storage'] = _STORAGE
DESCRIPTOR.message_types_by_name['ResultOfAction'] = _RESULTOFACTION
DESCRIPTOR.message_types_by_name['ExistsResult'] = _EXISTSRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StorageChange = _reflection.GeneratedProtocolMessageType('StorageChange', (_message.Message,), dict(
  DESCRIPTOR = _STORAGECHANGE,
  __module__ = 'membership_pb2'
  # @@protoc_insertion_point(class_scope:membership.StorageChange)
  ))
_sym_db.RegisterMessage(StorageChange)

AccountId = _reflection.GeneratedProtocolMessageType('AccountId', (_message.Message,), dict(
  DESCRIPTOR = _ACCOUNTID,
  __module__ = 'membership_pb2'
  # @@protoc_insertion_point(class_scope:membership.AccountId)
  ))
_sym_db.RegisterMessage(AccountId)

Storage = _reflection.GeneratedProtocolMessageType('Storage', (_message.Message,), dict(
  DESCRIPTOR = _STORAGE,
  __module__ = 'membership_pb2'
  # @@protoc_insertion_point(class_scope:membership.Storage)
  ))
_sym_db.RegisterMessage(Storage)

ResultOfAction = _reflection.GeneratedProtocolMessageType('ResultOfAction', (_message.Message,), dict(
  DESCRIPTOR = _RESULTOFACTION,
  __module__ = 'membership_pb2'
  # @@protoc_insertion_point(class_scope:membership.ResultOfAction)
  ))
_sym_db.RegisterMessage(ResultOfAction)

ExistsResult = _reflection.GeneratedProtocolMessageType('ExistsResult', (_message.Message,), dict(
  DESCRIPTOR = _EXISTSRESULT,
  __module__ = 'membership_pb2'
  # @@protoc_insertion_point(class_scope:membership.ExistsResult)
  ))
_sym_db.RegisterMessage(ExistsResult)



_MEMBERSHIPSERVER = _descriptor.ServiceDescriptor(
  name='MembershipServer',
  full_name='membership.MembershipServer',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=313,
  serialized_end=550,
  methods=[
  _descriptor.MethodDescriptor(
    name='SetStorageChange',
    full_name='membership.MembershipServer.SetStorageChange',
    index=0,
    containing_service=None,
    input_type=_STORAGECHANGE,
    output_type=_RESULTOFACTION,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SetTotalStorageChange',
    full_name='membership.MembershipServer.SetTotalStorageChange',
    index=1,
    containing_service=None,
    input_type=_STORAGECHANGE,
    output_type=_RESULTOFACTION,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetStorage',
    full_name='membership.MembershipServer.GetStorage',
    index=2,
    containing_service=None,
    input_type=_ACCOUNTID,
    output_type=_STORAGE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MEMBERSHIPSERVER)

DESCRIPTOR.services_by_name['MembershipServer'] = _MEMBERSHIPSERVER

# @@protoc_insertion_point(module_scope)
