# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import pbmsgbox_pb2 as pbmsgbox__pb2


class MsgboxServiceStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
        """Constructor.

        Args:
          channel: A grpc.Channel.
        """
        self.CreateGroupMessage = channel.unary_unary(
            '/pbmsgbox.MsgboxService/CreateGroupMessage',
            request_serializer=pbmsgbox__pb2.GroupMessageCreateRequest.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
        self.Add = channel.unary_unary(
            '/pbmsgbox.MsgboxService/Add',
            request_serializer=pbmsgbox__pb2.MessageAddRequests.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
        self.Query = channel.unary_unary(
            '/pbmsgbox.MsgboxService/Query',
            request_serializer=pbmsgbox__pb2.MessageQueryRequest.SerializeToString,
            response_deserializer=pbmsgbox__pb2.MessageQueryResponse.FromString,
        )
        self.Delete = channel.unary_unary(
            '/pbmsgbox.MsgboxService/Delete',
            request_serializer=pbmsgbox__pb2.MessageItemRequest.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
        self.DeleteAll = channel.unary_unary(
            '/pbmsgbox.MsgboxService/DeleteAll',
            request_serializer=pbmsgbox__pb2.MessageQueryAllRequest.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
        self.Read = channel.unary_unary(
            '/pbmsgbox.MsgboxService/Read',
            request_serializer=pbmsgbox__pb2.MessageItemRequest.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
        self.ReadAll = channel.unary_unary(
            '/pbmsgbox.MsgboxService/ReadAll',
            request_serializer=pbmsgbox__pb2.MessageQueryAllRequest.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
        self.UnRead = channel.unary_unary(
            '/pbmsgbox.MsgboxService/UnRead',
            request_serializer=pbmsgbox__pb2.MessageItemRequest.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
        self.GetUnReadCount = channel.unary_unary(
            '/pbmsgbox.MsgboxService/GetUnReadCount',
            request_serializer=pbmsgbox__pb2.MessageUnReadCountRequest.SerializeToString,
            response_deserializer=pbmsgbox__pb2.MessageUnReadCountResponse.FromString,
        )


class MsgboxServiceServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def CreateGroupMessage(self, request, context):
        """创建Group Message消息记录
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Add(self, request, context):
        """-----------------------------------------------------------------------------------------------------------------

        add message to someone
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Query(self, request, context):
        """query messages for someone
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """delete message
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAll(self, request, context):
        """delete all messages for someone
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Read(self, request, context):
        """set message as read
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadAll(self, request, context):
        """set all messages as read for someone
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnRead(self, request, context):
        """set message as unread
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUnReadCount(self, request, context):
        """-----------------------------------------------------------------------------------------------------------------

        get unread messages count
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MsgboxServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'CreateGroupMessage': grpc.unary_unary_rpc_method_handler(
            servicer.CreateGroupMessage,
            request_deserializer=pbmsgbox__pb2.GroupMessageCreateRequest.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
        'Add': grpc.unary_unary_rpc_method_handler(
            servicer.Add,
            request_deserializer=pbmsgbox__pb2.MessageAddRequests.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
        'Query': grpc.unary_unary_rpc_method_handler(
            servicer.Query,
            request_deserializer=pbmsgbox__pb2.MessageQueryRequest.FromString,
            response_serializer=pbmsgbox__pb2.MessageQueryResponse.SerializeToString,
        ),
        'Delete': grpc.unary_unary_rpc_method_handler(
            servicer.Delete,
            request_deserializer=pbmsgbox__pb2.MessageItemRequest.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
        'DeleteAll': grpc.unary_unary_rpc_method_handler(
            servicer.DeleteAll,
            request_deserializer=pbmsgbox__pb2.MessageQueryAllRequest.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
        'Read': grpc.unary_unary_rpc_method_handler(
            servicer.Read,
            request_deserializer=pbmsgbox__pb2.MessageItemRequest.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
        'ReadAll': grpc.unary_unary_rpc_method_handler(
            servicer.ReadAll,
            request_deserializer=pbmsgbox__pb2.MessageQueryAllRequest.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
        'UnRead': grpc.unary_unary_rpc_method_handler(
            servicer.UnRead,
            request_deserializer=pbmsgbox__pb2.MessageItemRequest.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
        'GetUnReadCount': grpc.unary_unary_rpc_method_handler(
            servicer.GetUnReadCount,
            request_deserializer=pbmsgbox__pb2.MessageUnReadCountRequest.FromString,
            response_serializer=pbmsgbox__pb2.MessageUnReadCountResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'pbmsgbox.MsgboxService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
