# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import pbpush_pb2 as pbpush__pb2


class PushServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.UpdateDevice = channel.unary_unary(
        '/pbpush.PushService/UpdateDevice',
        request_serializer=pbpush__pb2.Device.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.Send = channel.unary_unary(
        '/pbpush.PushService/Send',
        request_serializer=pbpush__pb2.PushJob.SerializeToString,
        response_deserializer=pbpush__pb2.PushJobID.FromString,
        )
    self.GetJobStatus = channel.unary_unary(
        '/pbpush.PushService/GetJobStatus',
        request_serializer=pbpush__pb2.PushJobID.SerializeToString,
        response_deserializer=pbpush__pb2.PushJobStatusResponse.FromString,
        )


class PushServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def UpdateDevice(self, request, context):
    """更新Device信息
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Send(self, request, context):
    """获取某用户所有的Device列表
    rpc ListDevices (QueryDevicesRequest) returns (DevicesResponse);

    -----------------------------------------------------------------------------------------------------------------

    推送给某个用户下所有的Device
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetJobStatus(self, request, context):
    """获取推送JOB的状态
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PushServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'UpdateDevice': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateDevice,
          request_deserializer=pbpush__pb2.Device.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'Send': grpc.unary_unary_rpc_method_handler(
          servicer.Send,
          request_deserializer=pbpush__pb2.PushJob.FromString,
          response_serializer=pbpush__pb2.PushJobID.SerializeToString,
      ),
      'GetJobStatus': grpc.unary_unary_rpc_method_handler(
          servicer.GetJobStatus,
          request_deserializer=pbpush__pb2.PushJobID.FromString,
          response_serializer=pbpush__pb2.PushJobStatusResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'pbpush.PushService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))