# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import pbrecord_pb2 as record__pb2


class RecordStub(object):
  """service Record
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.AddRecord = channel.unary_unary(
        '/record.Record/AddRecord',
        request_serializer=record__pb2.RecordDetail.SerializeToString,
        response_deserializer=record__pb2.ResultOfAction.FromString,
        )
    self.GetCurveData = channel.unary_unary(
        '/record.Record/GetCurveData',
        request_serializer=record__pb2.GrowthKey.SerializeToString,
        response_deserializer=record__pb2.GrowthData.FromString,
        )
    self.GetGrowthList = channel.unary_unary(
        '/record.Record/GetGrowthList',
        request_serializer=record__pb2.GetGrowthListRequest.SerializeToString,
        response_deserializer=record__pb2.GrowthList.FromString,
        )
    self.DeleteGrowthDetail = channel.unary_unary(
        '/record.Record/DeleteGrowthDetail',
        request_serializer=record__pb2.DeleteGrowthDetailRequest.SerializeToString,
        response_deserializer=record__pb2.ResultOfAction.FromString,
        )
    self.UpdateGrowthDetail = channel.unary_unary(
        '/record.Record/UpdateGrowthDetail',
        request_serializer=record__pb2.GrowthDetail.SerializeToString,
        response_deserializer=record__pb2.ResultOfAction.FromString,
        )
    self.GetBirthRecord = channel.unary_unary(
        '/record.Record/GetBirthRecord',
        request_serializer=record__pb2.GetBirthRecordRequest.SerializeToString,
        response_deserializer=record__pb2.BirthRecord.FromString,
        )


class RecordServicer(object):
  """service Record
  """

  def AddRecord(self, request, context):
    """add record
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetCurveData(self, request, context):
    """get  growth curve data
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetGrowthList(self, request, context):
    """get growth list
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteGrowthDetail(self, request, context):
    """delete growth
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateGrowthDetail(self, request, context):
    """update growth
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetBirthRecord(self, request, context):
    """get brith record
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RecordServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'AddRecord': grpc.unary_unary_rpc_method_handler(
          servicer.AddRecord,
          request_deserializer=record__pb2.RecordDetail.FromString,
          response_serializer=record__pb2.ResultOfAction.SerializeToString,
      ),
      'GetCurveData': grpc.unary_unary_rpc_method_handler(
          servicer.GetCurveData,
          request_deserializer=record__pb2.GrowthKey.FromString,
          response_serializer=record__pb2.GrowthData.SerializeToString,
      ),
      'GetGrowthList': grpc.unary_unary_rpc_method_handler(
          servicer.GetGrowthList,
          request_deserializer=record__pb2.GetGrowthListRequest.FromString,
          response_serializer=record__pb2.GrowthList.SerializeToString,
      ),
      'DeleteGrowthDetail': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteGrowthDetail,
          request_deserializer=record__pb2.DeleteGrowthDetailRequest.FromString,
          response_serializer=record__pb2.ResultOfAction.SerializeToString,
      ),
      'UpdateGrowthDetail': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateGrowthDetail,
          request_deserializer=record__pb2.GrowthDetail.FromString,
          response_serializer=record__pb2.ResultOfAction.SerializeToString,
      ),
      'GetBirthRecord': grpc.unary_unary_rpc_method_handler(
          servicer.GetBirthRecord,
          request_deserializer=record__pb2.GetBirthRecordRequest.FromString,
          response_serializer=record__pb2.BirthRecord.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'record.Record', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
