# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pbsms.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pbsms.proto',
  package='pbsms',
  syntax='proto3',
  serialized_pb=_b('\n\x0bpbsms.proto\x12\x05pbsms\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x95\x01\n\nSmsRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\x03\x12\x10\n\x08template\x18\x02 \x01(\t\x12\x0e\n\x06mobile\x18\x03 \x01(\t\x12\x0e\n\x06params\x18\x04 \x01(\t\x12\x0e\n\x06\x65xtend\x18\x05 \x01(\t\x12\x31\n\rexpiration_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2y\n\nSmsService\x12\x31\n\x04Send\x12\x11.pbsms.SmsRequest\x1a\x16.google.protobuf.Empty\x12\x38\n\x0bSendInstant\x12\x11.pbsms.SmsRequest\x1a\x16.google.protobuf.Emptyb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_SMSREQUEST = _descriptor.Descriptor(
  name='SmsRequest',
  full_name='pbsms.SmsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='product_id', full_name='pbsms.SmsRequest.product_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='template', full_name='pbsms.SmsRequest.template', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mobile', full_name='pbsms.SmsRequest.mobile', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='params', full_name='pbsms.SmsRequest.params', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='extend', full_name='pbsms.SmsRequest.extend', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='expiration_at', full_name='pbsms.SmsRequest.expiration_at', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=234,
)

_SMSREQUEST.fields_by_name['expiration_at'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['SmsRequest'] = _SMSREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SmsRequest = _reflection.GeneratedProtocolMessageType('SmsRequest', (_message.Message,), dict(
  DESCRIPTOR = _SMSREQUEST,
  __module__ = 'pbsms_pb2'
  # @@protoc_insertion_point(class_scope:pbsms.SmsRequest)
  ))
_sym_db.RegisterMessage(SmsRequest)



_SMSSERVICE = _descriptor.ServiceDescriptor(
  name='SmsService',
  full_name='pbsms.SmsService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=236,
  serialized_end=357,
  methods=[
  _descriptor.MethodDescriptor(
    name='Send',
    full_name='pbsms.SmsService.Send',
    index=0,
    containing_service=None,
    input_type=_SMSREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendInstant',
    full_name='pbsms.SmsService.SendInstant',
    index=1,
    containing_service=None,
    input_type=_SMSREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SMSSERVICE)

DESCRIPTOR.services_by_name['SmsService'] = _SMSSERVICE

# @@protoc_insertion_point(module_scope)
