# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import pbspace_pb2 as space__pb2


class SpaceStub(object):
  """service Space
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateSpace = channel.unary_unary(
        '/space.Space/CreateSpace',
        request_serializer=space__pb2.SpaceCreate.SerializeToString,
        response_deserializer=space__pb2.SpaceID.FromString,
        )
    self.UpdateSpaceInfo = channel.unary_unary(
        '/space.Space/UpdateSpaceInfo',
        request_serializer=space__pb2.Info.SerializeToString,
        response_deserializer=space__pb2.ResultOfAction.FromString,
        )
    self.UpdateSpaceStatus = channel.unary_unary(
        '/space.Space/UpdateSpaceStatus',
        request_serializer=space__pb2.Status.SerializeToString,
        response_deserializer=space__pb2.ResultOfAction.FromString,
        )
    self.SetFollower = channel.unary_unary(
        '/space.Space/SetFollower',
        request_serializer=space__pb2.FollowerData.SerializeToString,
        response_deserializer=space__pb2.ResultOfAction.FromString,
        )
    self.UpdateFollower = channel.unary_unary(
        '/space.Space/UpdateFollower',
        request_serializer=space__pb2.FollowerInfo.SerializeToString,
        response_deserializer=space__pb2.ResultOfAction.FromString,
        )
    self.UpdateFollowerPermission = channel.unary_unary(
        '/space.Space/UpdateFollowerPermission',
        request_serializer=space__pb2.FollowerData.SerializeToString,
        response_deserializer=space__pb2.ResultOfAction.FromString,
        )
    self.SearchFollower = channel.unary_unary(
        '/space.Space/SearchFollower',
        request_serializer=space__pb2.FollowerKey.SerializeToString,
        response_deserializer=space__pb2.FollowerData.FromString,
        )
    self.DeleteFollower = channel.unary_unary(
        '/space.Space/DeleteFollower',
        request_serializer=space__pb2.DeleteFollowerRequest.SerializeToString,
        response_deserializer=space__pb2.ResultOfAction.FromString,
        )
    self.GetSpaceDetailsBySpaceID = channel.unary_unary(
        '/space.Space/GetSpaceDetailsBySpaceID',
        request_serializer=space__pb2.SpaceID.SerializeToString,
        response_deserializer=space__pb2.SpaceDetails.FromString,
        )
    self.GetSpaceDetailsByOwnerID = channel.unary_unary(
        '/space.Space/GetSpaceDetailsByOwnerID',
        request_serializer=space__pb2.OwnerID.SerializeToString,
        response_deserializer=space__pb2.SpaceDetails.FromString,
        )
    self.GetSpaceDetailsByFollowerID = channel.unary_unary(
        '/space.Space/GetSpaceDetailsByFollowerID',
        request_serializer=space__pb2.FollowerID.SerializeToString,
        response_deserializer=space__pb2.AllSpaceDetails.FromString,
        )
    self.GetAuthSpaceDetailsByFollowerID = channel.unary_unary(
        '/space.Space/GetAuthSpaceDetailsByFollowerID',
        request_serializer=space__pb2.FollowerID.SerializeToString,
        response_deserializer=space__pb2.AllSpaceDetails.FromString,
        )
    self.GetAuthOwnerIDList = channel.unary_unary(
        '/space.Space/GetAuthOwnerIDList',
        request_serializer=space__pb2.FollowerID.SerializeToString,
        response_deserializer=space__pb2.SpaceAndOwnerIDList.FromString,
        )
    self.GetSpaceCount = channel.unary_unary(
        '/space.Space/GetSpaceCount',
        request_serializer=space__pb2.FollowerID.SerializeToString,
        response_deserializer=space__pb2.SpaceCount.FromString,
        )
    self.GetFollowerDetailsBySpaceID = channel.unary_unary(
        '/space.Space/GetFollowerDetailsBySpaceID',
        request_serializer=space__pb2.SpaceID.SerializeToString,
        response_deserializer=space__pb2.AllFollowerDetails.FromString,
        )
    self.SaveInviteCode = channel.unary_unary(
        '/space.Space/SaveInviteCode',
        request_serializer=space__pb2.SpaceIDCode.SerializeToString,
        response_deserializer=space__pb2.ResultOfAction.FromString,
        )
    self.GetInviteCode = channel.unary_unary(
        '/space.Space/GetInviteCode',
        request_serializer=space__pb2.SpaceID.SerializeToString,
        response_deserializer=space__pb2.InviteCode.FromString,
        )
    self.GetSpaceID = channel.unary_unary(
        '/space.Space/GetSpaceID',
        request_serializer=space__pb2.InviteCode.SerializeToString,
        response_deserializer=space__pb2.SpaceID.FromString,
        )
    self.GetAllRelation = channel.unary_unary(
        '/space.Space/GetAllRelation',
        request_serializer=space__pb2.Empty.SerializeToString,
        response_deserializer=space__pb2.RelationList.FromString,
        )
    self.AddRelation = channel.unary_unary(
        '/space.Space/AddRelation',
        request_serializer=space__pb2.Relation.SerializeToString,
        response_deserializer=space__pb2.ResultOfAction.FromString,
        )
    self.SetRelation = channel.unary_unary(
        '/space.Space/SetRelation',
        request_serializer=space__pb2.Relation.SerializeToString,
        response_deserializer=space__pb2.ResultOfAction.FromString,
        )
    self.DeleteRelation = channel.unary_unary(
        '/space.Space/DeleteRelation',
        request_serializer=space__pb2.RelationID.SerializeToString,
        response_deserializer=space__pb2.ResultOfAction.FromString,
        )
    self.GetRelationByRelationID = channel.unary_unary(
        '/space.Space/GetRelationByRelationID',
        request_serializer=space__pb2.RelationID.SerializeToString,
        response_deserializer=space__pb2.Relation.FromString,
        )
    self.GetAllGroup = channel.unary_unary(
        '/space.Space/GetAllGroup',
        request_serializer=space__pb2.SpaceID.SerializeToString,
        response_deserializer=space__pb2.GroupList.FromString,
        )
    self.AddGroup = channel.unary_unary(
        '/space.Space/AddGroup',
        request_serializer=space__pb2.AddGroupRequest.SerializeToString,
        response_deserializer=space__pb2.GroupID.FromString,
        )
    self.SetGroup = channel.unary_unary(
        '/space.Space/SetGroup',
        request_serializer=space__pb2.Info.SerializeToString,
        response_deserializer=space__pb2.ResultOfAction.FromString,
        )
    self.DeleteGroup = channel.unary_unary(
        '/space.Space/DeleteGroup',
        request_serializer=space__pb2.DeleteGroupRequest.SerializeToString,
        response_deserializer=space__pb2.ResultOfAction.FromString,
        )
    self.GetGroupByGroupID = channel.unary_unary(
        '/space.Space/GetGroupByGroupID',
        request_serializer=space__pb2.GroupID.SerializeToString,
        response_deserializer=space__pb2.Group.FromString,
        )
    self.GetGroupCountByGroupID = channel.unary_unary(
        '/space.Space/GetGroupCountByGroupID',
        request_serializer=space__pb2.GroupID.SerializeToString,
        response_deserializer=space__pb2.GroupCount.FromString,
        )
    self.GetDefaultGroupCountByGroupID = channel.unary_unary(
        '/space.Space/GetDefaultGroupCountByGroupID',
        request_serializer=space__pb2.SpaceID.SerializeToString,
        response_deserializer=space__pb2.GroupCount.FromString,
        )
    self.CheckPermission = channel.unary_unary(
        '/space.Space/CheckPermission',
        request_serializer=space__pb2.CheckPermissionRequest.SerializeToString,
        response_deserializer=space__pb2.ResultOfAction.FromString,
        )
    self.GetPermissionLevel = channel.unary_unary(
        '/space.Space/GetPermissionLevel',
        request_serializer=space__pb2.GetPermissionLevelRequest.SerializeToString,
        response_deserializer=space__pb2.Permission_Level.FromString,
        )


class SpaceServicer(object):
  """service Space
  """

  def CreateSpace(self, request, context):
    """Create space
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateSpaceInfo(self, request, context):
    """Update name, cover_image
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateSpaceStatus(self, request, context):
    """UpdateSpaceStatus
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetFollower(self, request, context):
    """set follower
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateFollower(self, request, context):
    """update follower
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateFollowerPermission(self, request, context):
    """update permission of follower
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SearchFollower(self, request, context):
    """search follower with key
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteFollower(self, request, context):
    """delete follower with key
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetSpaceDetailsBySpaceID(self, request, context):
    """Get space details by space id
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetSpaceDetailsByOwnerID(self, request, context):
    """Get space details by owner id
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetSpaceDetailsByFollowerID(self, request, context):
    """Get space details by follower id
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAuthSpaceDetailsByFollowerID(self, request, context):
    """获取当前账号具有修改权限的宝宝space详情列表
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAuthOwnerIDList(self, request, context):
    """
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetSpaceCount(self, request, context):
    """
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetFollowerDetailsBySpaceID(self, request, context):
    """Get follower details by space id
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SaveInviteCode(self, request, context):
    """save invite_code
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetInviteCode(self, request, context):
    """get invite_code
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetSpaceID(self, request, context):
    """get space_id by invite_code
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAllRelation(self, request, context):
    """get all relation
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddRelation(self, request, context):
    """add relation
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetRelation(self, request, context):
    """set relation
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteRelation(self, request, context):
    """delete relation
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetRelationByRelationID(self, request, context):
    """get relation
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAllGroup(self, request, context):
    """get all group
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddGroup(self, request, context):
    """add group
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetGroup(self, request, context):
    """set group
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteGroup(self, request, context):
    """delete group
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetGroupByGroupID(self, request, context):
    """get group by group_id
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetGroupCountByGroupID(self, request, context):
    """get group count by group_id
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetDefaultGroupCountByGroupID(self, request, context):
    """get default group count by space_id
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CheckPermission(self, request, context):
    """check follower permission
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPermissionLevel(self, request, context):
    """get permission level
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SpaceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateSpace': grpc.unary_unary_rpc_method_handler(
          servicer.CreateSpace,
          request_deserializer=space__pb2.SpaceCreate.FromString,
          response_serializer=space__pb2.SpaceID.SerializeToString,
      ),
      'UpdateSpaceInfo': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateSpaceInfo,
          request_deserializer=space__pb2.Info.FromString,
          response_serializer=space__pb2.ResultOfAction.SerializeToString,
      ),
      'UpdateSpaceStatus': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateSpaceStatus,
          request_deserializer=space__pb2.Status.FromString,
          response_serializer=space__pb2.ResultOfAction.SerializeToString,
      ),
      'SetFollower': grpc.unary_unary_rpc_method_handler(
          servicer.SetFollower,
          request_deserializer=space__pb2.FollowerData.FromString,
          response_serializer=space__pb2.ResultOfAction.SerializeToString,
      ),
      'UpdateFollower': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateFollower,
          request_deserializer=space__pb2.FollowerInfo.FromString,
          response_serializer=space__pb2.ResultOfAction.SerializeToString,
      ),
      'UpdateFollowerPermission': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateFollowerPermission,
          request_deserializer=space__pb2.FollowerData.FromString,
          response_serializer=space__pb2.ResultOfAction.SerializeToString,
      ),
      'SearchFollower': grpc.unary_unary_rpc_method_handler(
          servicer.SearchFollower,
          request_deserializer=space__pb2.FollowerKey.FromString,
          response_serializer=space__pb2.FollowerData.SerializeToString,
      ),
      'DeleteFollower': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteFollower,
          request_deserializer=space__pb2.DeleteFollowerRequest.FromString,
          response_serializer=space__pb2.ResultOfAction.SerializeToString,
      ),
      'GetSpaceDetailsBySpaceID': grpc.unary_unary_rpc_method_handler(
          servicer.GetSpaceDetailsBySpaceID,
          request_deserializer=space__pb2.SpaceID.FromString,
          response_serializer=space__pb2.SpaceDetails.SerializeToString,
      ),
      'GetSpaceDetailsByOwnerID': grpc.unary_unary_rpc_method_handler(
          servicer.GetSpaceDetailsByOwnerID,
          request_deserializer=space__pb2.OwnerID.FromString,
          response_serializer=space__pb2.SpaceDetails.SerializeToString,
      ),
      'GetSpaceDetailsByFollowerID': grpc.unary_unary_rpc_method_handler(
          servicer.GetSpaceDetailsByFollowerID,
          request_deserializer=space__pb2.FollowerID.FromString,
          response_serializer=space__pb2.AllSpaceDetails.SerializeToString,
      ),
      'GetAuthSpaceDetailsByFollowerID': grpc.unary_unary_rpc_method_handler(
          servicer.GetAuthSpaceDetailsByFollowerID,
          request_deserializer=space__pb2.FollowerID.FromString,
          response_serializer=space__pb2.AllSpaceDetails.SerializeToString,
      ),
      'GetAuthOwnerIDList': grpc.unary_unary_rpc_method_handler(
          servicer.GetAuthOwnerIDList,
          request_deserializer=space__pb2.FollowerID.FromString,
          response_serializer=space__pb2.SpaceAndOwnerIDList.SerializeToString,
      ),
      'GetSpaceCount': grpc.unary_unary_rpc_method_handler(
          servicer.GetSpaceCount,
          request_deserializer=space__pb2.FollowerID.FromString,
          response_serializer=space__pb2.SpaceCount.SerializeToString,
      ),
      'GetFollowerDetailsBySpaceID': grpc.unary_unary_rpc_method_handler(
          servicer.GetFollowerDetailsBySpaceID,
          request_deserializer=space__pb2.SpaceID.FromString,
          response_serializer=space__pb2.AllFollowerDetails.SerializeToString,
      ),
      'SaveInviteCode': grpc.unary_unary_rpc_method_handler(
          servicer.SaveInviteCode,
          request_deserializer=space__pb2.SpaceIDCode.FromString,
          response_serializer=space__pb2.ResultOfAction.SerializeToString,
      ),
      'GetInviteCode': grpc.unary_unary_rpc_method_handler(
          servicer.GetInviteCode,
          request_deserializer=space__pb2.SpaceID.FromString,
          response_serializer=space__pb2.InviteCode.SerializeToString,
      ),
      'GetSpaceID': grpc.unary_unary_rpc_method_handler(
          servicer.GetSpaceID,
          request_deserializer=space__pb2.InviteCode.FromString,
          response_serializer=space__pb2.SpaceID.SerializeToString,
      ),
      'GetAllRelation': grpc.unary_unary_rpc_method_handler(
          servicer.GetAllRelation,
          request_deserializer=space__pb2.Empty.FromString,
          response_serializer=space__pb2.RelationList.SerializeToString,
      ),
      'AddRelation': grpc.unary_unary_rpc_method_handler(
          servicer.AddRelation,
          request_deserializer=space__pb2.Relation.FromString,
          response_serializer=space__pb2.ResultOfAction.SerializeToString,
      ),
      'SetRelation': grpc.unary_unary_rpc_method_handler(
          servicer.SetRelation,
          request_deserializer=space__pb2.Relation.FromString,
          response_serializer=space__pb2.ResultOfAction.SerializeToString,
      ),
      'DeleteRelation': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteRelation,
          request_deserializer=space__pb2.RelationID.FromString,
          response_serializer=space__pb2.ResultOfAction.SerializeToString,
      ),
      'GetRelationByRelationID': grpc.unary_unary_rpc_method_handler(
          servicer.GetRelationByRelationID,
          request_deserializer=space__pb2.RelationID.FromString,
          response_serializer=space__pb2.Relation.SerializeToString,
      ),
      'GetAllGroup': grpc.unary_unary_rpc_method_handler(
          servicer.GetAllGroup,
          request_deserializer=space__pb2.SpaceID.FromString,
          response_serializer=space__pb2.GroupList.SerializeToString,
      ),
      'AddGroup': grpc.unary_unary_rpc_method_handler(
          servicer.AddGroup,
          request_deserializer=space__pb2.AddGroupRequest.FromString,
          response_serializer=space__pb2.GroupID.SerializeToString,
      ),
      'SetGroup': grpc.unary_unary_rpc_method_handler(
          servicer.SetGroup,
          request_deserializer=space__pb2.Info.FromString,
          response_serializer=space__pb2.ResultOfAction.SerializeToString,
      ),
      'DeleteGroup': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteGroup,
          request_deserializer=space__pb2.DeleteGroupRequest.FromString,
          response_serializer=space__pb2.ResultOfAction.SerializeToString,
      ),
      'GetGroupByGroupID': grpc.unary_unary_rpc_method_handler(
          servicer.GetGroupByGroupID,
          request_deserializer=space__pb2.GroupID.FromString,
          response_serializer=space__pb2.Group.SerializeToString,
      ),
      'GetGroupCountByGroupID': grpc.unary_unary_rpc_method_handler(
          servicer.GetGroupCountByGroupID,
          request_deserializer=space__pb2.GroupID.FromString,
          response_serializer=space__pb2.GroupCount.SerializeToString,
      ),
      'GetDefaultGroupCountByGroupID': grpc.unary_unary_rpc_method_handler(
          servicer.GetDefaultGroupCountByGroupID,
          request_deserializer=space__pb2.SpaceID.FromString,
          response_serializer=space__pb2.GroupCount.SerializeToString,
      ),
      'CheckPermission': grpc.unary_unary_rpc_method_handler(
          servicer.CheckPermission,
          request_deserializer=space__pb2.CheckPermissionRequest.FromString,
          response_serializer=space__pb2.ResultOfAction.SerializeToString,
      ),
      'GetPermissionLevel': grpc.unary_unary_rpc_method_handler(
          servicer.GetPermissionLevel,
          request_deserializer=space__pb2.GetPermissionLevelRequest.FromString,
          response_serializer=space__pb2.Permission_Level.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'space.Space', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
