# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import pbwxcc_pb2 as pbwxcc__pb2


class WxCCServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.MiniProgramLogin = channel.unary_unary(
        '/pbwxcc.WxCCService/MiniProgramLogin',
        request_serializer=pbwxcc__pb2.MiniProgramLoginRequest.SerializeToString,
        response_deserializer=pbwxcc__pb2.MiniProgramLoginResponse.FromString,
        )
    self.MiniProgramSetAccountPair = channel.unary_unary(
        '/pbwxcc.WxCCService/MiniProgramSetAccountPair',
        request_serializer=pbwxcc__pb2.MiniProgramSetAccountPairRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.MiniProgramDecryptUserInfo = channel.unary_unary(
        '/pbwxcc.WxCCService/MiniProgramDecryptUserInfo',
        request_serializer=pbwxcc__pb2.EncryptedUserinfo.SerializeToString,
        response_deserializer=pbwxcc__pb2.Userinfo.FromString,
        )
    self.OpenAppLogin = channel.unary_unary(
        '/pbwxcc.WxCCService/OpenAppLogin',
        request_serializer=pbwxcc__pb2.OpenAppLoginRequest.SerializeToString,
        response_deserializer=pbwxcc__pb2.Userinfo.FromString,
        )
    self.OpenAppSetAccountPair = channel.unary_unary(
        '/pbwxcc.WxCCService/OpenAppSetAccountPair',
        request_serializer=pbwxcc__pb2.OpenAppSetAccountPairRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )


class WxCCServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def MiniProgramLogin(self, request, context):
    """Login. fetch openid session_key unionid by code
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def MiniProgramSetAccountPair(self, request, context):
    """保存account_id与LoginResponse的匹配项
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def MiniProgramDecryptUserInfo(self, request, context):
    """DecryptUserInfo 解密userinfo
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def OpenAppLogin(self, request, context):
    """DecryptPhoneNumber 解密phone number
    rpc DecryptPhoneNumber(EncryptedData) returns (PhoneNumber);

    ----------------------------------------------------------------------------------------------

    OpenAppLogin.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def OpenAppSetAccountPair(self, request, context):
    """保存account_id与LoginResponse的匹配项
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_WxCCServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'MiniProgramLogin': grpc.unary_unary_rpc_method_handler(
          servicer.MiniProgramLogin,
          request_deserializer=pbwxcc__pb2.MiniProgramLoginRequest.FromString,
          response_serializer=pbwxcc__pb2.MiniProgramLoginResponse.SerializeToString,
      ),
      'MiniProgramSetAccountPair': grpc.unary_unary_rpc_method_handler(
          servicer.MiniProgramSetAccountPair,
          request_deserializer=pbwxcc__pb2.MiniProgramSetAccountPairRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'MiniProgramDecryptUserInfo': grpc.unary_unary_rpc_method_handler(
          servicer.MiniProgramDecryptUserInfo,
          request_deserializer=pbwxcc__pb2.EncryptedUserinfo.FromString,
          response_serializer=pbwxcc__pb2.Userinfo.SerializeToString,
      ),
      'OpenAppLogin': grpc.unary_unary_rpc_method_handler(
          servicer.OpenAppLogin,
          request_deserializer=pbwxcc__pb2.OpenAppLoginRequest.FromString,
          response_serializer=pbwxcc__pb2.Userinfo.SerializeToString,
      ),
      'OpenAppSetAccountPair': grpc.unary_unary_rpc_method_handler(
          servicer.OpenAppSetAccountPair,
          request_deserializer=pbwxcc__pb2.OpenAppSetAccountPairRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'pbwxcc.WxCCService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
