# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import pbzid_pb2 as pbzid__pb2


class ZIDServiceStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
        """Constructor.

        Args:
          channel: A grpc.Channel.
        """
        self.Query = channel.unary_unary(
            '/pbzid.ZIDService/Query',
            request_serializer=pbzid__pb2.IDRequest.SerializeToString,
            response_deserializer=pbzid__pb2.IDResponse.FromString,
        )
        self.QueryEncode58 = channel.unary_unary(
            '/pbzid.ZIDService/QueryEncode58',
            request_serializer=pbzid__pb2.IDRequest.SerializeToString,
            response_deserializer=pbzid__pb2.IDBase58Response.FromString,
        )


class ZIDServiceServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def Query(self, request, context):
        """获取全局唯一ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryEncode58(self, request, context):
        """获取全局唯一ID（使用58进制编码的字符串）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ZIDServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'Query': grpc.unary_unary_rpc_method_handler(
            servicer.Query,
            request_deserializer=pbzid__pb2.IDRequest.FromString,
            response_serializer=pbzid__pb2.IDResponse.SerializeToString,
        ),
        'QueryEncode58': grpc.unary_unary_rpc_method_handler(
            servicer.QueryEncode58,
            request_deserializer=pbzid__pb2.IDRequest.FromString,
            response_serializer=pbzid__pb2.IDBase58Response.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'pbzid.ZIDService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
